export const SPECIALTIES = [
  "cardiology",
  "neurology",
  "orthopedics",
  "pediatrics",
  "general_surgery",
  "emergency_medicine",
  "internal_medicine",
  "oncology",
  "obstetrics",
  "gynecology",
  "nephrology",
  "pulmonology",
  "gastroenterology",
  "urology",
  "dermatology",
  "ophthalmology",
  "ent",
  "psychiatry",
] as const;

export type Specialty = (typeof SPECIALTIES)[number];

export const SPECIALTY_ALIASES: Record<string, Specialty> = {
  cardiologist: "cardiology",
  "heart doctor": "cardiology",
  "heart specialist": "cardiology",
  neurologist: "neurology",
  orthopedist: "orthopedics",
  orthopedic: "orthopedics",
  "bone doctor": "orthopedics",
  pediatrician: "pediatrics",
  "child specialist": "pediatrics",
  surgeon: "general_surgery",
  "general surgeon": "general_surgery",
  "emergency doctor": "emergency_medicine",
  "emergency physician": "emergency_medicine",
  physician: "internal_medicine",
  obgyn: "obstetrics",
  "ob-gyn": "obstetrics",
  eye_doctor: "ophthalmology",
  ophthalmologist: "ophthalmology",
  ent_specialist: "ent",
  ent_doctor: "ent",
};
